import React, { useState } from 'react'
import { useShop } from '../context/ShopContext'

export default function ShopOverlays() {
  const { loginOpen, setLoginOpen, cartOpen, setCartOpen, cart, total, updateQuantity, order, setOrder, login, toast, setToast } = useShop()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [mode, setMode] = useState('login')
  const [name, setName] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); const result = await login({ email, password, name, createAccount: mode === 'create' }); setSubmitting(false); if (result.error) return setError(result.error); setPassword('') }
  return <>
    {loginOpen && <div className="shop-overlay" role="dialog" aria-modal="true"><div className="shop-login-modal"><button className="shop-modal-close" onClick={() => setLoginOpen(false)}>x</button><p className="shop-kicker">{mode === 'create' ? 'Create your account' : 'Welcome back'}</p><h2>{mode === 'create' ? 'Start shopping with ShopSphere' : 'Login to continue shopping'}</h2><p className="shop-modal-copy">Your account and login details are securely verified through Supabase.</p><form onSubmit={submit}>{mode === 'create' && <label>Name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" required /></label>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" minLength="6" required /></label>{error && <p className="shop-form-error" role="alert">{error}</p>}<button className="btn btn-primary shop-full-btn" type="submit" disabled={submitting}>{submitting ? 'Please wait...' : mode === 'create' ? 'Create Account' : 'Login'}</button></form><div className="shop-modal-links"><button onClick={() => setToast('Password reset requires Supabase Auth setup.')}>Forgot password?</button><button onClick={() => { setMode(mode === 'login' ? 'create' : 'login'); setError('') }}>{mode === 'login' ? 'Create account' : 'Already have an account?'}</button></div></div></div>}
    {cartOpen && <div className="shop-drawer-wrap"><button className="shop-drawer-backdrop" onClick={() => setCartOpen(false)} /><aside className="shop-cart-drawer"><header><div><span className="shop-kicker">Your selection</span><h2>Your Cart ({cart.length})</h2></div><button className="shop-modal-close" onClick={() => setCartOpen(false)}>x</button></header>{cart.length === 0 ? <div className="shop-empty-cart">Your cart is waiting for something great.</div> : <><div className="shop-cart-items">{cart.map((item) => <article key={item.key}><img src={item.image} alt="" /><div><h3>{item.name}</h3><p>{item.size}{item.color ? ` / ${item.color}` : ''}</p><strong>${item.price * item.quantity}</strong><div className="shop-quantity compact"><button onClick={() => updateQuantity(item.key, item.quantity - 1)}>-</button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.key, item.quantity + 1)}>+</button></div></div></article>)}</div><footer><div><span>Total</span><strong>${total}</strong></div><button className="btn btn-primary shop-full-btn" onClick={() => { setCartOpen(false); setToast('Checkout is ready.') }}>Checkout</button></footer></>}</aside></div>}
    {order && <div className="shop-overlay" role="dialog" aria-modal="true"><div className="shop-order-modal"><button className="shop-modal-close" onClick={() => setOrder(null)}>x</button><span className="shop-kicker">Order summary</span><h2>Review your order</h2><div className="shop-order-product"><img src={order.image} alt="" /><div><h3>{order.name}</h3><p>Size: {order.size}</p>{order.color && <p>Color: {order.color}</p>}<p>Quantity: {order.quantity}</p></div></div><div className="shop-order-total"><span>Total</span><strong>${order.price * order.quantity}</strong></div><button className="btn btn-primary shop-full-btn" onClick={() => { setOrder(null); setToast('Order confirmed.') }}>Confirm Order</button></div></div>}
    {toast && <div className="shop-toast" role="status">{toast}</div>}
  </>
}
